version: "2"
services:
  wordpress:
    image: wordpress:4.7.1-php7.1-apache
    volumes:
      - "./var/www/html:/var/www/html"
    ports:
      - "127.0.0.1:3456:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      TZ: Asia/Tokyo
    env_file: .env
  db:
    image: mysql:5.6.35
    volumes:
      - "./var/mysql:/var/lib/mysql"
    env_file: .env
